#!/usr/bin/env python3
"""Convert the owner's square WeChat payment QR into an LVGL RGB565 asset."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


SIZE = 176


def rgb565_swapped_bytes(image: Image.Image) -> list[int]:
    values: list[int] = []
    for red, green, blue in image.convert("RGB").getdata():
        pixel = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        # This project uses LV_COLOR_16_SWAP=y. Store the wire-order high byte first.
        values.extend((pixel >> 8, pixel & 0xFF))
    return values


def clean_qr(image: Image.Image) -> Image.Image:
    """Remove JPEG ringing from QR modules while preserving the center badge."""
    image = image.convert("RGB")
    width, height = image.size
    pixels = image.load()
    center = (width * 31 // 100, height * 31 // 100,
              width * 69 // 100, height * 69 // 100)
    for y in range(height):
        for x in range(width):
            if center[0] <= x < center[2] and center[1] <= y < center[3]:
                continue
            red, green, blue = pixels[x, y]
            luminance = (red * 299 + green * 587 + blue * 114) // 1000
            value = 0 if luminance < 128 else 255
            pixels[x, y] = (value, value, value)
    return image


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("c_output", type=Path)
    parser.add_argument("preview", type=Path)
    args = parser.parse_args()

    source = clean_qr(Image.open(args.input))
    resized = source.resize((SIZE, SIZE), Image.Resampling.NEAREST)
    resized.save(args.preview)
    values = rgb565_swapped_bytes(resized)
    rows = []
    for offset in range(0, len(values), 16):
        rows.append("    " + ", ".join(
            f"0x{value:02x}" for value in values[offset:offset + 16]) + ",")
    data = "\n".join(rows)
    args.c_output.write_text(f"""// Generated by tools/generate_donation_qr.py. Do not edit by hand.
#include "assets/donation_qr.h"

LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST static const uint8_t donation_qr_map[] = {{
{data}
}};

const lv_img_dsc_t donation_qr = {{
    .header.always_zero = 0,
    .header.w = {SIZE},
    .header.h = {SIZE},
    .data_size = sizeof(donation_qr_map),
    .header.cf = LV_IMG_CF_TRUE_COLOR,
    .data = donation_qr_map,
}};
""", encoding="utf-8")


if __name__ == "__main__":
    main()
