#!/usr/bin/env python3
"""Rasterize the product heart SVG into two LVGL A8 masks.

The firmware keeps the editable SVG as the source of truth, but renders tiny
precomputed alpha masks: no SVG parser, font glyph, or concave polygon is used
on the device. The outline is derived from the same silhouette as the fill.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path


SIZE = 24
SUPERSAMPLE = 4
STROKE_WIDTH = 1.55


def svg_polygon(svg: str) -> list[tuple[float, float]]:
    match = re.search(r'<path\s+[^>]*d="([^"]+)"', svg)
    if not match:
        raise ValueError("SVG must contain one path with a d attribute")
    tokens = re.findall(r"[MLCZ]|[-+]?(?:\d*\.\d+|\d+)", match.group(1))
    points: list[tuple[float, float]] = []
    index = 0
    current = (0.0, 0.0)
    start = current
    while index < len(tokens):
        command = tokens[index]
        index += 1
        if command == "M":
            current = (float(tokens[index]), float(tokens[index + 1]))
            index += 2
            start = current
            points.append(current)
        elif command == "L":
            current = (float(tokens[index]), float(tokens[index + 1]))
            index += 2
            points.append(current)
        elif command == "C":
            c1 = (float(tokens[index]), float(tokens[index + 1]))
            c2 = (float(tokens[index + 2]), float(tokens[index + 3]))
            end = (float(tokens[index + 4]), float(tokens[index + 5]))
            index += 6
            origin = current
            for step in range(1, 25):
                t = step / 24.0
                u = 1.0 - t
                points.append((
                    u**3 * origin[0] + 3 * u * u * t * c1[0] + 3 * u * t * t * c2[0] + t**3 * end[0],
                    u**3 * origin[1] + 3 * u * u * t * c1[1] + 3 * u * t * t * c2[1] + t**3 * end[1],
                ))
            current = end
        elif command == "Z":
            if points[-1] != start:
                points.append(start)
            current = start
        else:
            raise ValueError(f"unsupported SVG command: {command}")
    return points


def inside(point: tuple[float, float], polygon: list[tuple[float, float]]) -> bool:
    x, y = point
    result = False
    j = len(polygon) - 1
    for i, (xi, yi) in enumerate(polygon):
        xj, yj = polygon[j]
        if (yi > y) != (yj > y):
            cross_x = (xj - xi) * (y - yi) / (yj - yi) + xi
            if x < cross_x:
                result = not result
        j = i
    return result


def segment_distance(point: tuple[float, float], a: tuple[float, float],
                     b: tuple[float, float]) -> float:
    px, py = point
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    length_sq = dx * dx + dy * dy
    if length_sq == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / length_sq))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def rasterize(polygon: list[tuple[float, float]], outline: bool) -> list[int]:
    values: list[int] = []
    samples = SUPERSAMPLE * SUPERSAMPLE
    for y in range(SIZE):
        for x in range(SIZE):
            covered = 0
            for sy in range(SUPERSAMPLE):
                for sx in range(SUPERSAMPLE):
                    point = (x + (sx + 0.5) / SUPERSAMPLE,
                             y + (sy + 0.5) / SUPERSAMPLE)
                    if not inside(point, polygon):
                        continue
                    if outline:
                        distance = min(segment_distance(point, polygon[i - 1], polygon[i])
                                       for i in range(len(polygon)))
                        if distance > STROKE_WIDTH:
                            continue
                    covered += 1
            values.append(round(255 * covered / samples))
    return values


def array(name: str, values: list[int]) -> str:
    rows = []
    for offset in range(0, len(values), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in values[offset:offset + 16]) + ",")
    data = "\n".join(rows)
    return f"""LV_ATTRIBUTE_MEM_ALIGN static const uint8_t {name}_map[] = {{
{data}
}};

const lv_img_dsc_t {name} = {{
    .header.always_zero = 0,
    .header.w = {SIZE},
    .header.h = {SIZE},
    .data_size = sizeof({name}_map),
    .header.cf = LV_IMG_CF_ALPHA_8BIT,
    .data = {name}_map,
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("svg", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    polygon = svg_polygon(args.svg.read_text(encoding="utf-8"))
    generated = """// Generated by tools/generate_heart_icon.py. Do not edit by hand.
#include "assets/heart_icon.h"

""" + array("heart_icon_outline", rasterize(polygon, True)) + "\n" + \
        array("heart_icon_filled", rasterize(polygon, False))
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
